version: '2'
mpp-vars:
  name: mycontainer-manifest
  use_containers_extra_store: true
  use_composefs: false

pipelines:
- name: rootfs
  build: name:build
  stages:

  # Install some RPMs
  - type: org.osbuild.rpm
    options:
      gpgkeys:
      - mpp-eval: distro_gpg_keys
      disable_dracut: true
      exclude:
        docs: true
    inputs:
      packages:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-depsolve:
          architecture: $arch
          ignore-weak-deps: true
          module-platform-id: $distro_module_id
          baseurl: $distro_baseurl_repo
          repos:
            mpp-join:
            - mpp-eval: image_repos
            - mpp-eval: extra_repos
            - - id: copr_can_utils
                baseurl: https://download.copr.fedorainfracloud.org/results/@centos-automotive-sig/can-utils/centos-stream-9-$arch/
              - id: copr_validator
                baseurl: https://download.copr.fedorainfracloud.org/results/@centos-automotive-sig/validator/centos-stream+epel-next-9-$arch/
          packages:
            mpp-join:
            - mpp-eval: image_rpms
            - - vim
              - dnf
              - podman
              - tar
              - validator
              - tree
              - openssh-clients
              - openssh-server

  # Get the CS9 base container in
  - type: org.osbuild.skopeo
    inputs:
      images:
        type: org.osbuild.containers
        origin: org.osbuild.source
        mpp-resolve-images:
          images:
            - source: quay.io/centos/centos
              tag: stream9
              name: localhost/cs9
    options:
      destination:
        type: containers-storage
        storage-path:
          mpp-eval: containers_extra_store

  # Ensures /etc/systemd/system/basic.target.wants/ exists before we put
  # something theree
  - type: org.osbuild.mkdir
    options:
      paths:
      - path: /etc/systemd/system/basic.target.wants/
        parents: true

  # Get a V1 quadlet
  # Install the public key used by validator
  # Install the dracut module for validator
  # Add the validator service as a plain systemd service
  - type: org.osbuild.copy
    inputs:
      inlinefile1:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: app_v1.container
          path: ./files/app_v1.container
      inlinefile2:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: public.pem
          path: ./files/public.pem
      inlinefile3:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: validator.boot
          path: ./files/validator.boot
      inlinefile4:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-embed:
          id: validator.service
          path: ./files/validator.service
    options:
      paths:
      - from:
          mpp-format-string: input://inlinefile1/{embedded['app_v1.container']}
        to: tree:///etc/containers/systemd/app_v1.container
      - from:
          mpp-format-string: input://inlinefile2/{embedded['public.pem']}
        to: tree:///usr/lib/validator/keys/etc.key
      - from:
          mpp-format-string: input://inlinefile3/{embedded['validator.boot']}
        to: tree:///etc/validator/boot.d/validator.boot
      - from:
          mpp-format-string: input://inlinefile4/{embedded['validator.service']}
        to: tree:///etc/systemd/system/validator.service

  # Create the guest user
  - type: org.osbuild.users
    options:
      users:
        guest:
          password: "$6$xoLqEUz0cGGJRx01$H3H/bFm0myJPULNMtbSsOFd/2BnHqHkMD92Sfxd.EKM9hXTWSmELG8cf205l6dktomuTcgKGGtGDgtvHVXSWU."
          gid: 999
          uid: 999
